# Generated by Django 3.0.5 on 2020-05-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPMFilm', '0002_auto_20200429_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_rating',
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.URLField(),
        ),
    ]
