# Generated by Django 3.0.5 on 2020-06-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPMFilm', '0003_auto_20200507_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
