# Generated by Django 3.0.5 on 2020-06-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UPMFilm', '0005_remove_film_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='UPMFilm.Genre'),
        ),
    ]
